config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  get '/about' => 'homes#about'

  # アカウント認証
  get "login" => "sessions#login_form" # link_toメソッドではデフォルトでgetのルーティングを探す
  post "login" => "sessions#login" # form_withメソッドではデフォルトでpostのルーティングを探す
  delete "logout" => "sessions#logout"

  # posts これからコメント機能やいいね機能など他にも機能を追加していく予定なのでその時にresourcesに変える
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  post "posts/create" => "posts#create"
  get "posts/:id" => "posts#show"
  get "posts/:id/edit" => "posts#edit"
  patch "posts/:id/update" => "posts#update"
  delete "posts/:id/destroy" => "posts#destroy"

  # users
  get "signup" => "users#new" # サインアップ(ユーザー登録)時のフォーム画面を「/users/new」ではなく「signup」というURLで表示したかったためresourcesとは分けている。
  resources :users, only: [:index, :show, :create, :edit, :update] # onlyで特定のアクションのみを指定
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, {presence: true, length:{maximum: 10}}
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, {presence: true, length:{maximum: 10}} # 空でなければパスする&文字は最大10文字まで
    validates :email, {presence: true, uniqueness: true} # 空でなければパスする&同じカラムのメールアドレスは保存されない
    validates :password, {presence: true} # 空でなければパスする
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # 全アクションで共通する処理(before_actionは他のアクションを呼び出す前に先行して呼び出す)
    before_action :current_user
    
    # 全てのコントローラで共通する処理がある場合はapplicationコントローラにまとめる
    def current_user # 現在のユーザー
      @current_user = User.find_by(id: session[:user_id]) # usersテーブルのidカラムの値がsession[:user_id](ログインしているユーザーのid)と等しいユーザー情報を取得する
    end

    def authenticate_user # ユーザの認証
      if @current_user == nil # 現在のユーザーとnilが等しいならば(ユーザーがログインしていなければログイン後のページにアクセスできない)
        flash[:notice] = "ログインもしくはサインアップを行ってください"
        redirect_to("/login")
      end
    end 

    def forbid_login_user # ログインユーザーの禁止
      if @current_user
        flash[:notice] = "既にログイン済みです"
        redirect_to("/posts/index")
      end
    end

    def ensure_correct_user # 正しいユーザーであるか確認
      if @current_user.id != params[:id].to_i # ログイン中のユーザーidと編集したいユーザーのidが異なる場合(params[:id]で取得できる値は文字列であるため.to_iで数値に置き換えている)
        flash[:notice] = "他のユーザー情報を編集することは出来ません"
        redirect_to users_path
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top        
    end

    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 各コントローラの各アクションで共通する処理(全アクションに適用しない場合)
  before_action :authenticate_user

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all.order(content: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to posts_index_path
    else
      render("posts/new")
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      flash[:notice] = "編集に成功しました"
      redirect_to posts_index_path
    else
      render("posts/edit")
    end
  end

  def destroy
    post = Post.find_by(id: params[:id])
    post.destroy
    flash[:notice] = "削除に成功しました"
    redirect_to posts_index_path    
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # 各コントローラの各アクションで共通する処理
  before_action :forbid_login_user, {only: [:login_form, :login]} # onlyを用いて指定したアクションでのみメソッドが適用される

  # アカウント認証機能のアクション
  def login_form
  end

  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id # 特定のユーザのidをsession変数に代入することで、特定のログインユーザの情報をブラウザに保存する
      flash[:notice] = "ログインしました"
      redirect_to("/posts/index")
    else
      @error_message = "メールアドレスまたはパスワードが異なります"
      render("sessions/login_form")
    end
  end

  def logout
    session[:user_id] = nil # session変数に代入されている値をnil(空)にしてログアウト状態にする
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 各コントローラの各アクションで共通する処理(全アクションに適用しない場合)
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]} # onlyを用いて指定したアクションでのみメソッドが適用される
  before_action :forbid_login_user, {only: [:new, :create]}
  before_action :ensure_correct_user, {only: [:edit, :update]}

  # users機能のアクション
  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集に成功しました"
      redirect_to user_path
    else
      render("users/edit")
    end
  end

  # サインアップ(ユーザー登録)のアクション
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザの登録に成功しました"
      redirect_to("/posts/index")
    else
      render("users/new")
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="about-main">
  <div class="about-message">
    <h2>自由にrailsを勉強する場とは</h2>
    <p>学習したことを1つの作品を作りながらアウトプットする場です。<br>
      まずは簡単なブログサイトを目標に、railsのmvcの流れと基本の７アクションをマスターしていきます。

    </p>
    
    <p> 
      その後、付加価値としてdeviceやransackなどの業務で必要になるであろうgemの知識や<br>
      非同期処理・アソシエーション・rubyで苦手としてる内容などを学習し、<br>
      この場で自由にアウトプットし必要であればレビューを頂くなど業務で通用するrailsの素養をつける場です。
    </p>

    <div class="top-link">
      <%= link_to 'TOPページへ戻る', '/' %>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="top-main">
  <div class="top-message">
    <h2>自由にrailsを勉強する場</h2>
    <p>口ではなんでも言える。ひとまず手を動かそう</p>
    
    <div class="about-link">
      <%= link_to '詳しくはこちら＝＞', '/about' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="header-menus">
        <% if @current_user %>
          <li>
            <!-- 現在ログインしているユーザーの詳細ページに遷移させる -->
            現在ログインしているユーザー:
            <%= link_to(@current_user.name, user_path(@current_user.id)) %> 
          </li>

          <li>
            <%= link_to("投稿一覧", "/posts/index") %>
          </li>

          <li>
            <%= link_to("新規投稿", "/posts/new") %>
          </li>

          <li>
            <%= link_to("ユーザ一覧", users_path) %>
          </li>

           <li>
             <%= link_to("ログアウト", "/logout", {method: "delete"}) %>
           </li>
        <% else %>
          <li>
            <%= link_to("自由にrailsを勉強する場とは", "/about") %>
          </li>

          <li>
            <%= link_to("ログイン", "/login") %>
          </li>

          <li>
            <%= link_to("サインアップ", "/signup") %>
          </li>
        <% end %>
      </ul>
    </header>

    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h2>投稿編集</h2>
      <div class="error-message">
         <% @post.errors.full_messages.each do |message| %>
             <%= message %>
         <% end %>
      </div>

    <%= form_with(model: @post, url:"/posts/#{@post.id}/update", local: true) do |form| %>
      <%= form.text_field :content %>
      <%= form.submit '更新する' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
  　<h2>投稿一覧</h2>
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <%= link_to(post.content, "/posts/#{post.id}") %>
      </div>
    <% end %>

    <div class="new-link">
      <%= link_to('新規投稿はこちら=>', '/posts/new') %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
  <h2>新規投稿</h2>
    <div class="error-massage">
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
    
    <!-- モデルのみだとNoMethodError undefined method `***_path'が発生する。どこに飛ばすのかurlを指定 -->
    <%= form_with model: @post, url: posts_create_path, local: true do |form| %>
      <%= form.text_field :content %>
      <%= form.submit '投稿する' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
  <h2>投稿詳細</h2>
    <div class="posts-show-item">
      <p>
        <%= @post.content %>
      </p>
      <div class="post-time">
        <!-- Time::strftimeメソッドを使用し「UTC:時差」を消して見栄えをよくしている -->
        <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %>
      </div>
    </div>

    <div class="edit-link">
      <%= link_to("編集する", "/posts/#{@post.id}/edit") %>
    </div>

    <div class="destroy-link">
      <%= link_to("削除する", "/posts/#{@post.id}/destroy", {method: "delete"}) %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
  　<h2>ユーザ一編集</h2>
    <div class="error-message">
      <% @user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>

    <%= form_with(model: @user, url: user_path, local: true) do |f| %>
      <%= f.text_field :name %>
      <%= f.email_field :email %>
      <%= f.password_field :password %>
      <%= f.submit "更新する" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
  　<h2>ユーザ 一覧</h2>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <%= link_to(user.name, user_path(user.id)) %> <!-- link_to(user.name, "/users/#{user.id}")と同じこと -->
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users_signup-form">
      <div class="form-body">
        <%= form_with(model: @user, url: users_path, local: true) do |f| %>
          <div class="error-message">
            <% @user.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          </div>

          <!-- form_withで使用できるhtmlタグをしっかり確認しておくこと！ -->
          <%= f.text_field :name %>
          <%= f.email_field :email %>
          <%= f.password_field :password %>
          <%= f.submit "ユーザーを登録する" %>
        <% end %>
      </div>
    </div>       
  </div>
</div>

app/views/users/show.html.erb
<div class="main users-show">
  <div class="container">
  　<h2>ユーザ一詳細</h2>
    <div class="users-show-item">
      <p>
        <%= @user.name %>
      </p>
    </div>

    <div class="edit-link">
      <% if @user.id == @current_user.id %> <!-- 詳細ページのユーザー(id)とログインしている現在のユーザー(id)が等しい場合は編集ページに遷移できる -->
        <%= link_to("編集する", edit_user_path) %> <!-- link_to("編集する", "/users/#{@user.id}/edit") と同じこと -->
      <% end %>
    </div>
  </div>
</div>